server:
  port: 7001

eureka:
  instance:
    #hostname: localhost  #eureka服务端的实例名称
    hostname: eureka7001.com  #eureka服务端的实例名称

  client:
    fetch-registry: false   #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    register-with-eureka: false  #false表示不向注册中心注册自己。
    service-url:
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
      defaultZone: http://eureka7002.com:7002/eureka

  server:
    enable-self-preservation: false  #关闭自我保护机制，保证不可用服务被及时踢除
    eviction-interval-timer-in-ms: 2000   #2秒内客户端没有发生心跳，就剔除

